"""Fetch the PECD population-weighting mask.

Methodology: PECD v4.2 (Pan-European Climate Database), section 2.4
"Population-weighted Temperature" -
https://confluence.ecmwf.int/spaces/CKB/pages/540941752/. The population
grid (NASA SEDAC 2020 data, regridded by ECMWF to 0.25 deg) is distributed
as a ready-made NetCDF mask via the Copernicus Climate Data Store, dataset
`sis-energy-pecd`, "Weights and masks" widget.

*** CURRENTLY FAKED ***: USE_FAKE_MASK = True below generates a synthetic
population-density-like raster (Gaussian bumps at Germany's largest
cities) instead of calling the real CDS API - good enough to exercise
02_build_germany_mask.py and the downstream Germany temperature
comparison end-to-end, but NOT real population data; don't read anything
quantitative into the resulting comparison plot until this is switched
off. Flip USE_FAKE_MASK to False (and fill in CDS_REQUEST) once a CDS
account/API key (~/.cdsapirc) is available - see
https://cds.climate.copernicus.eu/how-to-api and `pip install cdsapi`
into the GPU venv this project's pipeline scripts run against. The exact
CDS_REQUEST dict is generated by the CDS website's interactive "Weights
and masks" widget once logged in and a product is selected -
https://cds.climate.copernicus.eu/datasets/sis-energy-pecd

Deliberately split from 02_build_germany_mask.py: that script's Germany
crop + regrid-to-native-grid logic is identical whether the raw file
below came from the real CDS download or this fake stand-in, so swapping
one for the other never touches it.
"""

import numpy as np
import xarray as xr

from e2s.paths import ProjPaths

paths = ProjPaths()
paths.ensure_directories()

USE_FAKE_MASK = True  # flip to False once a CDS account/API key exists

CDS_DATASET = "sis-energy-pecd"
# TODO: replace with the real request dict from the CDS website's
# "Weights and masks" widget (Download tab, population-weighting product).
CDS_REQUEST = {
    # "variable": "???",
    # "origin": "???",
    # "product_type": "???",
}

raw_path = paths.germany_population_mask_raw_path

# Roughly Germany + neighbors - generous enough that 02_build_germany_mask.py's
# crop-to-Germany doesn't run off the edge of this fake domain.
FAKE_LAT = np.arange(35.0, 70.0 + 1e-9, 0.25)
FAKE_LON = np.arange(-10.0, 30.0 + 1e-9, 0.25)

# A handful of Germany's largest cities (lat, lon, rough population in
# millions) - just enough spatial structure (higher "population" in and
# around real cities, near-zero in between) to make the population- vs.
# area-weighted comparison visually meaningful. Not a claim of real
# population data - see USE_FAKE_MASK above.
FAKE_CITIES = [
    (52.520, 13.405, 3.6),   # Berlin
    (53.551, 9.993, 1.8),    # Hamburg
    (48.137, 11.575, 1.5),   # Munich
    (50.938, 6.960, 1.1),    # Cologne
    (50.111, 8.682, 0.75),   # Frankfurt
    (51.228, 6.773, 0.62),   # Duesseldorf
    (51.340, 12.375, 0.60),  # Leipzig
    (48.783, 9.182, 0.63),   # Stuttgart
]
FAKE_CITY_SIGMA_DEG = 0.6  # spatial spread of each city's population bump


def build_fake_population_raster():
    lon_grid, lat_grid = np.meshgrid(FAKE_LON, FAKE_LAT)
    population = np.zeros_like(lon_grid)
    for city_lat, city_lon, weight_millions in FAKE_CITIES:
        d2 = (lat_grid - city_lat) ** 2 + (lon_grid - city_lon) ** 2
        population += weight_millions * 1e6 * np.exp(-d2 / (2 * FAKE_CITY_SIGMA_DEG ** 2))
    return xr.Dataset(
        {"population": (("lat", "lon"), population)},
        coords={"lat": FAKE_LAT, "lon": FAKE_LON},
        attrs={
            "note": "SYNTHETIC PLACEHOLDER - not real PECD/SEDAC population "
                    "data. Generated by pipeline/germany/01_run.py's "
                    "build_fake_population_raster() until a CDS API key is "
                    "available; see this script's module docstring.",
        },
    )


def download_real_pecd_population_mask():
    import cdsapi  # deferred: only required once CDS access is set up

    print(f"Downloading '{CDS_DATASET}' population mask from CDS...")
    client = cdsapi.Client()
    client.retrieve(CDS_DATASET, CDS_REQUEST, str(raw_path))


def main():
    if raw_path.exists():
        print(f"Using cached raw mask at {raw_path}")
        return

    if USE_FAKE_MASK:
        print("[FAKE] USE_FAKE_MASK=True - generating a synthetic placeholder "
              "population raster, NOT real PECD/SEDAC data.")
        build_fake_population_raster().to_netcdf(raw_path)
        print(f"Saved fake population raster to {raw_path}")
    else:
        download_real_pecd_population_mask()
        print(f"Saved raw PECD population mask to {raw_path}")


if __name__ == "__main__":
    main()
